trigger:
  - master

variables:
  packages: |
    bison \
    re2c \
    locales \
    language-pack-de \
    re2c \
    libgmp-dev \
    libicu-dev \
    libtidy-dev \
    libenchant-dev \
    libaspell-dev \
    libpspell-dev \
    librecode-dev \
    libsasl2-dev \
    libxpm-dev \
    libzip-dev \
    libsqlite3-dev \
    libwebp-dev \
    libonig-dev \
    libkrb5-dev \
    libgssapi-krb5-2 \
    libcurl4-openssl-dev \
    libxml2-dev \
    libxslt1-dev \
    libpq-dev \
    libreadline-dev

  configuration: |
    --prefix=/usr \
    --enable-phpdbg \
    --enable-fpm \
    --with-pdo-mysql=mysqlnd \
    --with-mysqli=mysqlnd \
    --with-pgsql \
    --with-pdo-pgsql \
    --with-pdo-sqlite \
    --enable-intl \
    --without-pear \
    --enable-gd \
    --with-jpeg \
    --with-webp \
    --with-freetype \
    --with-xpm \
    --enable-exif \
    --enable-zip \
    --with-zlib \
    --with-zlib-dir=/usr \
    --enable-soap \
    --enable-xmlreader \
    --with-xsl \
    --with-tidy \
    --with-xmlrpc \
    --enable-sysvsem \
    --enable-sysvshm \
    --enable-shmop \
    --enable-pcntl \
    --with-readline \
    --enable-mbstring \
    --with-curl \
    --with-gettext \
    --enable-sockets \
    --with-bz2 \
    --with-openssl \
    --with-gmp \
    --enable-bcmath \
    --enable-calendar \
    --enable-ftp \
    --with-pspell=/usr \
    --with-enchant=/usr \
    --with-kerberos \
    --enable-sysvmsg \
    --with-ffi \
    --enable-zend-test=shared \
    --enable-werror \
    --with-config-file-dir=/etc \
    --with-config-file-scan-dir=/etc/php.d
  
  run: |
    TEST_PHP_JUNIT=junit.xml php run-tests.php -P \
                                               -j$(/usr/bin/nproc) \
                                               -q \
                                               -g "FAIL,XFAIL,BORK,WARN,LEAK,SKIP" \
                                               --offline \
                                               --show-diff \
                                               --show-slow 1000 \
                                               --set-timeout 120

jobs:
  - job: NO_DEBUG_NO_ZTS
    pool:
      vmImage: "ubuntu-latest"
    steps:
    - script: sudo apt-get update -y | true
      displayName: "APT UPDATE"
    - script: sudo apt install $(packages)
      displayName: "APT INSTALL"
    - script: ./buildconf --force
      displayName: "BUILDCONF"
    - script: ./configure --disable-debug --disable-zts $(configuration)
      displayName: "CONFIGURE"
    - script: make -j$(/usr/bin/nproc)
      displayName: "MAKE"
    - script: sudo make install
      displayName: "INSTALL"
    - script: $(run)
      displayName: "TEST"
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'junit.xml'
        testRunTitle: 'PHP Test Suite'
  - job: DEBUG_NO_ZTS
    pool:
      vmImage: "ubuntu-latest"
    steps:
    - script: sudo apt-get update | true
      displayName: "APT UPDATE"
    - script: sudo apt install $(packages)
      displayName: "APT INSTALL"
    - script: ./buildconf --force
      displayName: "BUILDCONF"
    - script: ./configure --enable-debug --disable-zts $(configuration)
      displayName: "CONFIGURE"
    - script: make -j$(/usr/bin/nproc)
      displayName: "MAKE"
    - script: sudo make install
      displayName: "INSTALL"
    - script: $(run)
      displayName: "TEST"
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'junit.xml'
        testRunTitle: 'PHP Test Suite'
  - job: NO_DEBUG_ZTS
    pool:
      vmImage: "ubuntu-latest"
    steps:
    - script: sudo apt-get update | true
      displayName: "APT UPDATE"
    - script: sudo apt install $(packages)
      displayName: "APT INSTALL"
    - script: ./buildconf --force
      displayName: "BUILDCONF"
    - script: ./configure --disable-debug --enable-zts $(configuration)
      displayName: "CONFIGURE"
    - script: make -j$(/usr/bin/nproc)
      displayName: "MAKE"
    - script: sudo make install
      displayName: "INSTALL"
    - script: $(run)
      displayName: "TEST"
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'junit.xml'
        testRunTitle: 'PHP Test Suite'
  - job: DEBUG_ZTS
    pool:
      vmImage: "ubuntu-latest"
    steps:
    - script: sudo apt-get update | true
      displayName: "APT UPDATE"
    - script: sudo apt install $(packages)
      displayName: "APT INSTALL"
    - script: ./buildconf --force
      displayName: "BUILDCONF"
    - script: ./configure --enable-debug --enable-zts $(configuration)
      displayName: "CONFIGURE"
    - script: make -j$(/usr/bin/nproc)
      displayName: "MAKE"
    - script: sudo make install
      displayName: "INSTALL"
    - script: $(run)
      displayName: "TEST"
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'junit.xml'
        testRunTitle: 'PHP Test Suite'