# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt-get update
  displayName: "APT Update"

- script: |
    sudo apt-get install  bison \
                          re2c \
                          locales \
                          language-pack-de \
                          re2c \
                          libgmp-dev \
                          libicu-dev \
                          libtidy-dev \
                          libenchant-dev \
                          libaspell-dev \
                          libpspell-dev \
                          librecode-dev \
                          libsasl2-dev \
                          libxpm-dev \
                          libzip-dev \
                          libsqlite3-dev \
                          libwebp-dev \
                          libonig-dev \
                          libkrb5-dev \
                          libgssapi-krb5-2 \
                          libcurl4-openssl-dev \
                          libxml2-dev \
                          libpq-dev
  displayName: 'Install APT Packages'

- script: |
    ./buildconf --force
  displayName: 'Build Configure Script'

- script: |
    ./configure --prefix=/usr \
                --enable-phpdbg \
                --enable-fpm \
                --with-pdo-mysql=mysqlnd \
                --with-mysqli=mysqlnd \
                --with-pgsql \
                --with-pdo-pgsql \
                --with-pdo-sqlite \
                --enable-intl \
                --without-pear \
                --enable-gd \
                --with-jpeg \
                --with-webp \
                --with-freetype \
                --with-xpm \
                --enable-exif \
                --enable-zip \
                --with-zlib \
                --with-zlib-dir=/usr \
                --enable-soap \
                --enable-xmlreader \
                --with-xsl \
                --with-tidy \
                --with-xmlrpc \
                --enable-sysvsem \
                --enable-sysvshm \
                --enable-shmop \
                --enable-pcntl \
                --with-readline \
                --enable-mbstring \
                --with-curl \
                --with-gettext \
                --enable-sockets \
                --with-bz2 \
                --with-openssl \
                --with-gmp \
                --enable-bcmath \
                --enable-calendar \
                --enable-ftp \
                --with-pspell=/usr \
                --with-enchant=/usr \
                --with-kerberos \
                --enable-sysvmsg \
                --with-ffi \
                --enable-zend-test=shared \
                --enable-werror
  displayName: "Configure Build"

- script: |
    make -j4
  displayName: "Build"

- script: |
    make install
  displayName: "Install"
